### ISSUE TITLE
TargetNotMemberException is thrown when starting a transaction with disabling smartRouting and redoOperation

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-csharp-client#139] opened 2017-11-15 15:11 UTC
When a transaction is tried to be started with disabling `smartRouting` and `redoOperation`, the folllowing exception is thrown:

![image](https://user-images.githubusercontent.com/7557235/32843235-2aa06230-ca17-11e7-97be-945d2506d735.png)

The stacktrace is as follows:

```
   at Hazelcast.Client.Proxy.TransactionProxy.Begin()
   at Hazelcast.Client.Proxy.TransactionContextProxy.BeginTransaction()
   at ConsoleApplication3.Program.Main(String[] args) in c:\Users\Alparslan\Documents\Visual Studio 2013\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 79
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by asimarslan** [comment] 2017-11-16 10:36
Closing this issue in favor of the root cause bug #140

**Closed by asimarslan** 2017-11-16 10:36 UTC
