### ISSUE TITLE
Hazelcast query long(Int64) type doesn't work NOT IN condition

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#161] opened 2018-03-23 05:58 UTC
I try to use `NOT IN` but I am not successed. It is throw:
`InvalidOperationException: Exception of type 'System.InvalidOperationException' was thrown.` and lots of map and property name.

My query: `Id NOT IN ( 13, 17, 22533)`

So I try that: `Id NOT IN ( 13L, 17L, 22533L)` In that case, exception thrown like `HazelcastException: 'For input string: "13L"'`

Then I change my query to  `Id IN ( 13, 17, 22533)`, it worked.

Why IN condition is working but NOT IN condition is not working, I still dont understand.

**Comment by asimarslan** [comment] 2018-06-21 13:37
Hi @iozcelik,

The problem with your usage is the `L` notation. You don't add L in long type queries.

`NOT IN` should just work if you write `Id NOT IN ( 13, 17, 22533)`

**Comment by iozcelik** [comment] 2018-07-25 14:51
Hi @asimarslan ,

As you explain [that issue](https://github.com/hazelcast/hazelcast-csharp-client/issues/150), I try it. But is not working.

**Comment by sancar** [comment] 2019-03-01 15:08
Can you share a full code sample that demonstrates the problem?

**Comment by iozcelik** [comment] 2019-03-02 06:58
My class and main methods like that: 
```
public class Customer : IPortable {
        public const int ClassId = 1;

        public string Name { get; set; }
        public long Id { get; set; }
        public DateTime LastOrder { get; set; }
       

        public int GetFactoryId() {
            return ExamplePortableFactory.Id;
        }

        public int GetClassId() {
            return ClassId;
        }

        public void WritePortable(IPortableWriter writer) {
            writer.WriteLong("Id", Id);
            writer.WriteUTF("Name", Name);
            writer.WriteLong("LastOrder", LastOrder.ToFileTimeUtc());
        }

        public void ReadPortable(IPortableReader reader) {
            Id = reader.ReadLong("Id");
            Name = reader.ReadUTF("Name");
            LastOrder = DateTime.FromFileTimeUtc(reader.ReadLong("LastOrder"));
        }

        public override string ToString() {
            return string.Format("Name: {0}, Id: {1}, LastOrder: {2}", Name, Id, LastOrder);
        }
    }

var config = new ClientConfig();
config.GetNetworkConfig().AddAddress("10.1.1.108");
config.SetGroupConfig(new GroupConfig("test","test"));
config.GetSerializationConfig().AddPortableFactory(ExamplePortableFactory.Id,new ExamplePortableFactory());
client = HazelcastClient.NewHazelcastClient(config);
            


var map = client.GetMap<long,Customer>("simple-example2");
for(var x = 1000000; x < 1000010; x++) {
                try {
                    map.Set(x,new Customer { Id = x,Name = "Name-" + x,LastOrder = DateTime.Now.AddHours(x) });
                } catch(Exception e) {
                    Console.WriteLine(e);
                }
            }

var keySet = map.Values(Predicates.Sql("Id  NOT IN (100,101,102,103,1000000)")).ToList();
```
![image](https://user-images.githubusercontent.com/10682780/53678502-09195f80-3cd1-11e9-83a1-9d074121077a.png)

I catch a point but I am not use about this. I use first letter capital when seriliazing my portable classes, also this capital in query but my guess, it is a problem.

**Comment by sancar** [comment] 2019-03-04 07:10
When I run the code I get 9 items. I did not get the item with Id 1000000.
One theory that could lead to this problem is using the wrong field name. If you did serialize the Customer.ID with the lower case against the member once it memorized that and causing wrong results. (meaning write was `writer.WriteLong("id", Id);` at some point by mistake )
I assume running the same code against a freshly started node will result in the correct result.

For example, I run this code and get 9 items first. 
Then I just changed the query to 
`Predicates.Sql("id  NOT IN (100,101,102,103,1000000)"`
This results in 10 items. 
Any field name that does not exist on Customer object results with 10 items.
`Predicates.Sql("nonExistingField  NOT IN (100,101,102,103,1000000)"`

**Comment by sancar** [comment] 2019-03-05 12:55
@iozcelik Did you have a chance to check my latest comment and verify?

**Comment by iozcelik** [comment] 2019-03-05 15:36
@sancar I check my code. However my serilization method above. So I still use it testing and getting same result. For note, I have no code at server side.

**Comment by sancar** [comment] 2019-03-05 16:17
I understand that you don't have any code on the server. I am also testing with a server without any config. 
Did you test with a fresh server? If not please restart your server and try the same code you shared above/ The server can keep the metadata from a client. If you don't restart your server, it could return a wrong number of items because of an old faulty client. 
When I run your code it returns 9 items, not 10. So you should also see the same result. 

Can you also give the exact version of the hazelcast client and hazelcast server that you are using?

**Comment by iozcelik** [comment] 2019-03-05 18:35
Ok, you are right about that. When I restart, it is worked. But still it does not solve my problem :)  Because I have multiple c# clients. One of them could query like that. After a while the problem shown again. 

My server version: 3.11.2
C# clients all of them: 3.10

**Comment by sancar** [comment] 2019-03-06 07:33
Note that querying with the wrong field does not affect the server and other clients. It only returns the wrong result where the query is done. 

If there is a client that does `writer.WriteLong("id", Id);` with wrong name, this could affect the server and other clients. Since restarting solved your problem, I think there is a problem with your `WritePortable` method in one of your clients.

Since restart solves your problem, you need to replace your faulty clients with correct ones and restart the server one final time. Since the mystery is solved and this is not a bug but a wrong usage, I am closing the issue.

**Closed by sancar** 2019-03-06 07:33 UTC
Labels: Type: Defect
