### ISSUE TITLE
The transactional put latency increases dramatically when smartRouting=false

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-csharp-client#138] opened 2017-11-15 14:57 UTC
When smart routing is disabled, transactional put operation performance drops dramatically. It can be reproduced by using the code snipped below:

```
var config = new ClientConfig();
config.GetGroupConfig().SetName("manc").SetPassword("manc-pass");
config.GetNetworkConfig().AddAddress("127.0.0.1:5701")
    .SetSmartRouting(false)
    .SetRedoOperation(true);

var client = HazelcastClient.NewHazelcastClient(config);
var map = client.GetMap<int, String>("test");
var map2 = client.GetMap<int, String>("test3");
map.Clear();
map2.Clear();

long totalDuration = 0;
int count = 100;
for (int i = 0; i < count; i++)
{
    TransactionOptions options = new TransactionOptions()
        .SetTransactionType(TransactionOptions.TransactionType.TwoPhase);
    ITransactionContext context = client.NewTransactionContext(options);

    var watch = System.Diagnostics.Stopwatch.StartNew();

    context.BeginTransaction();
    var tmap = context.GetMap<int, String>("test");
    var tmap2 = context.GetMap<int, String>("test2");

    tmap.Set(i, "value");
    tmap2.Set(i, "value");
    context.CommitTransaction();

    watch.Stop();
    totalDuration += watch.ElapsedMilliseconds;
}
Console.WriteLine((double)totalDuration / count);
```

Java client performs well with the same scenario. The regular put throughput is also good with disabling smart routing. Here are the sample latency outputs from the same setup:

.NET Client: ~1500ms
Java Client: ~5ms

**Comment by asimarslan** [comment] 2017-11-16 10:35
Closing this issue in favor of the root cause bug #140

**Closed by asimarslan** 2017-11-16 10:35 UTC
