### ISSUE TITLE
Leaking Handles when reconnecting 

### ISSUE THREAD

**Issue by MBoden67** [hazelcast/hazelcast-csharp-client#119] opened 2017-09-27 13:03 UTC
Handle leaking occur when reconnecting to server

can be reproduced by continually trying to connect to a nonexisting server 

           

>  ClientConfig HazelConfig = null;
            IHazelcastInstance instance = null;

            HazelConfig = new ClientConfig();
            HazelConfig.GetNetworkConfig().AddAddress("10.10.10.123");

            bool connected = false;
            while (!connected)
            {
                try
                {
                    Program.instance = HazelcastClient.NewHazelcastClient(Program.HazelConfig);

                    //                    ConnectToHazelcast();
                    connected = true;
                }
                catch (Exception)
                {

                }
            }

**Comment by asimarslan** [comment] 2017-10-09 13:04
Hi @MBoden67 ,
Can you give more detail on the issue? Are you talking about windows handles ? Can you detail how you reproduce it ?

**Comment by MBoden67** [comment] 2017-10-09 13:56
The Code to reproduce it is in the issue above

run the code against a nonexistent hazelcast server, set up performance monitor on "handle count" and watch it rise 

if you're impatient you can add 

HazelConfig.GetNetworkConfig().SetConnectionAttemptLimit(0); 

or 

HazelConfig.GetNetworkConfig().SetConnectionAttemptLimit(1); 

which seems to get it to climb faster

**Comment by asimarslan** [comment] 2017-10-10 12:00
After some tests, it looks like there is no handle leak. But as socket's has a lingering option that keep sockets's handle unallocated, for a period of time these handles waits the socket-linger period.
After that period we see a sharp deallocation of handles.

User can configure .net client's Socket linger period with

`clientConfig.GetNetworkConfig().GetSocketOptions().SetLingerSeconds(3)`

But unfortunately, setting a zero value does not disable it altogether. I made a [fix](https://github.com/hazelcast/hazelcast-csharp-client/pull/124) for this which will be released in next version (3.9)

Thanks @MBoden67 for your bug report, It also revealed another issue.

**Comment by MBoden67** [comment] 2017-10-11 11:45
I just let my testcode run for 3 hour and 18 minutes

it went from using 622 handles to using 59964 handles , se attached images

![handleleak20171011-3hourslater](https://user-images.githubusercontent.com/32331017/31438859-4128e5d4-ae8a-11e7-9cdf-417521078c72.png)
![handleleak20171011start](https://user-images.githubusercontent.com/32331017/31438860-414867d8-ae8a-11e7-86ff-b9096ed4a959.png)

The running code :

`			ClientConfig HazelConfig = null;
			IHazelcastInstance instance = null;

			Hazelcast.Logging.Logger.SetLoggerFactory(new HazelLogger());

            HazelConfig = new ClientConfig();

            HazelConfig.GetNetworkConfig().AddAddress("10.10.15.123");
            HazelConfig.GetNetworkConfig().SetConnectionAttemptLimit(1);
            HazelConfig.GetNetworkConfig().GetSocketOptions().SetLingerSeconds(3);


            bool connected = false;
            while(!connected)
            {
                try
                {
                    Program.instance = HazelcastClient.NewHazelcastClient(Program.HazelConfig);
                   
                    //                    ConnectToHazelcast();
                    connected = true;
                }
                catch (Exception)
                {
                    int ix = 1;
                }
            }            
			
	
	class HazelLogger : ILoggerFactory, ILogger
    {
        public ILogger GetLogger(string name)
        {
            return this;
        }

        public void Finest(string message)
        {
            this.Log(LogLevel.Finest, message);
        }

        public void Finest(Exception thrown)
        {
            this.Log(LogLevel.Finest, "Exception raised",thrown);
        }

        public void Finest(string message, Exception thrown)
        {
            this.Log(LogLevel.Finest, message, thrown);
        }

        public LogLevel GetLevel()
        {
            return LogLevel.All;
        }

        public void Info(string message)
        {
            this.Log(LogLevel.Info, message);
        }

        public bool IsFinestEnabled()
        {
            return true;
        }

        public bool IsLoggable(LogLevel level)
        {
            return true;
        }

        public void Log(LogLevel level, string message)
        {
            Console.WriteLine($"{DateTime.Now.ToLongTimeString()} [{level.ToString()}] : {message}");
        }

        public void Log(LogLevel level, string message, Exception thrown)
        {
            Console.WriteLine($"{DateTime.Now.ToLongTimeString()} [{level.ToString()}] : {message} , {thrown.Message}");
        }

        public void Severe(string message)
        {
            this.Log(LogLevel.Severe, message);
        }

        public void Severe(Exception thrown)
        {
            this.Log(LogLevel.Severe, "Exception raised",thrown);
        }

        public void Severe(string message, Exception thrown)
        {
            this.Log(LogLevel.Severe, message, thrown);
        }

        public void Warning(string message)
        {
            this.Log(LogLevel.Warning, message);
        }

        public void Warning(Exception thrown)
        {
            this.Log(LogLevel.Warning,"Exception raised", thrown);
        }

        public void Warning(string message, Exception thrown)
        {
            this.Log(LogLevel.Severe, message, thrown);
        }
    }`

**Comment by asimarslan** [comment] 2017-10-18 14:01
fixed by #125

**Closed by asimarslan** 2017-10-18 14:01 UTC
Labels: Type: Defect
