### ISSUE TITLE
Deserialization issue between Windows and Linux

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-csharp-client#103] opened 2017-03-02 12:47 UTC
There seems to be an issue using the .NET Client with Windows to Linux server, works with a Windows server. Could be a big-endian / little-endian difference.

Tech-stack:
 .Net version 4.5
·         Windows version: Windows 7 (for client) Windows server 2012 (if I am running Hazelcast server on Windpows)
·         Hazelcast client version 3.7.1
·         Linux version: Debian GNU/Linux8 (jessie)
·         Hazelcast server version : 3.7.5
·         Java :
o   openjdk version "1.8.0_111"
o   OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
o   OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

No further details yet...

**Comment by ohryhorchuk** [comment] 2017-03-02 12:56
This issue was reported from our Infrastructure. If anyone who is going to work with it needs more info - please feel free to contact me: oleksandr.hryhorchuk@nordea.dk

Thanks

**Comment by stalek71** [comment] 2019-03-11 11:28
Does the issue still appear on the client site?
@ohryhorchuk ?

**Comment by ohryhorchuk** [comment] 2019-03-11 11:52
We have stopped using Hazelcast because of it very long time ago.
I imagine it is still there, as no one has changed serialisation routines (as far as I can see).
But yes, not relevant for me anymore for sure

**Comment by stalek71** [comment] 2019-03-11 12:12
Sorry to hear that. I'm closing this issue in such case. 
The communication protocol uses Little Endian format so it should not cause any issues at all because of this.

**Comment by ohryhorchuk** [comment] 2019-03-11 12:16
Should not and not causing are different things, right? :)
You might, however, want to reproduce it.

**Comment by stalek71** [comment] 2019-03-11 14:11
Do you remember anything that could help me to reproduce such issue? 
You mentioned it can be little/big endian issue.
Does it mean you were using hosts with (potentially) different endian configurations (maybe some kind of risc processors for instance on linux hosts)?

**Comment by ohryhorchuk** [comment] 2019-03-11 17:24
It was a client running on windows 7 and hazelcast running on servers with Linux red hat (or centos). X86 based for sure, no risc - that I remember 100%.
Also, as far as I can remember, when I tried to debug things it was indeed little/big endian related issue. I looked at series of bytes with wire shark .
I hope this helps :-)
Good luck 🍀

**Comment by stalek71** [comment] 2019-03-12 14:00
Thanks!
It could be the case you were observing serialization with two distinct endian configurations in one message for instance. I have seen such predefined order of bytes here for instance in this [code fragment](https://github.com/hazelcast/hazelcast-csharp-client/blob/e9bc51411cf1831899a519455f8ab551c7d18f48/Hazelcast.Net/Hazelcast.IO.Serialization/SerializationService.cs#L111). 
I will verify this case/configuration mentioned by you in the nearest time for sure.

**Closed by stalek71** 2019-03-12 14:00 UTC
Labels: Estimation: M, Priority: Low, Type: Defect
