### ISSUE TITLE
PagingPredicate not working

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#212] opened 2019-01-23 14:56 UTC
I use the Customer class in the Hazelcast.Examples.Models project.

Sql predicate is working. No problem occured there. However, when using paging predicate that exception thrown "Could not find PortableFactory for factory-id:"

```
var map = client.GetMap<long, Customer>("simple-example1");
for (var x = 0; x < 100; x++) {
    try {
          map.Set(x, new Customer { Id = x, Name = "Name-" + x, LastOrder = DateTime.Now.AddHours(x) });
     } catch (Exception e) {
        Console.WriteLine(e);
     }
}


var sqlPredicate = Predicates.Sql("id>51");
var pagingPredicate = new PagingPredicate(10) { Page = 1 };

//working
var sqlPredicateResult = map.Values(sqlPredicate).ToList();
//exception thrown
var pagingPredicateResult = map.Values(pagingPredicate).ToList();
```

**Comment by hkilimci** [comment] 2019-01-25 07:06
This issue is hopeless. 

Seriously. 

I had reported [the same issue ages ago](https://github.com/hazelcast/hazelcast/issues/13900) and got replied that I would be updated **in a few days**. I now realize that I have opened the issue on the wrong subcategory. I accept that's my fault however I'd written that I was using c# client. 

But no chance.

Try to find another way of doing this.

**Comment by stalek71** [comment] 2019-01-25 12:14
I think the issue is because you have not registered portable serialization factory on server side also.
This is what I see on my side after running your simple snippet...

![image](https://user-images.githubusercontent.com/6651025/51745417-0eb4d180-20a3-11e9-9611-152c97e301bc.png)

**Comment by iozcelik** [comment] 2019-01-25 13:17
@stalek71 Then why does it succesfully return the values when I use the same class with Sql Predicate as an example below?

```
var sqlPredicate = Predicates.Sql("id>51");
//working
var sqlPredicateResult = map.Values(sqlPredicate).ToList();
```

**Comment by hkilimci** [comment] 2019-01-25 13:20
> I think the issue is because you have not registered portable serialization factory on server side also/yet.
> This is what I see on my side after running your code snippet...
> 
> ![image](https://user-images.githubusercontent.com/6651025/51745417-0eb4d180-20a3-11e9-9611-152c97e301bc.png)

@stalek71 If you have a look at my examples, without server side registering, I can get the values unless the map has more than some (I believe randomly) numbers of items.

**Comment by stalek71** [comment] 2019-01-25 13:49
It looks when you send a condition based on field directly (like in case of "id>51") it has everything it needs to compare&find entities. When you take data without specifying the condition (just "first page of data") it gives you the data based on "generic" order (paging needs predictable conditions to look for the data so it can't take just "random" set of data from data store on every (next) call).
I think java side just needs implementation of Comparable interface on class it deserializes to make it working predictable way. 
@hkilimci, I just reviewed screenshots you attached to the [issue](https://github.com/hazelcast/hazelcast/issues/13900) description and on [SO](https://stackoverflow.com/questions/52117115/hazelcast-paging-predicate-not-working-properly-when-map-has-over-a-spesific-num) and it doesn't show how you implemented comparison operator on java side. If possible please send more info when you create such description because I don't see all the aspects you took into account (just to verify it's bug on comparison operator implementation or maybe server sends you wrong answer when you provided all the conditions proper way)

**Comment by iozcelik** [comment] 2019-01-25 14:04
Can I not use this without writing any piece of code on Java side? Because I have only 5 lines of code on Java. The .net client that I use works on any other implementations except Paging Predicate.

**Comment by iozcelik** [comment] 2019-01-25 14:06
Besides, @hkilimci says that he can achieve without writing on Java server side.

**Comment by stalek71** [comment] 2019-01-25 14:22
I feel your pain writing something for java side only :)
I read/heard somewhere that the idea could be to provide some "order info" as part of Paging stuff.
When I read protocol doc I don't see such feature there at the moment, but I know Hazelcast is focused on simplifying our work so let's see... 
I wonder also if @hkilimci could share his code with us just to show incorrect behavior of such code.
If possible please share it with us (at least in some simple form)...

**Comment by dbrimley** [comment] 2019-02-08 07:33
@hkilimci if you could share a simple reproducer of your issue I can ask one of the engineers to take a look at it.

**Comment by hkilimci** [comment] 2019-02-13 13:54
@stalek71 @dbrimley I am adding a very simple reproduce of my codes below.

I am assuming you already have data on the map. 

So; Main method on **Program.cs:**

```
using System.Collections.Generic;

namespace MyHazelcastTest {
    class Program {
        static void Main(string[] args) {

            var hzuow = new HazelCastUnitOfWork();

            var repo = hzuow.GetRepository();

            var entityList = new List<CommInImdb>();

            for (var i = 0; i < 50; i++) {
                var entry = new CommInImdb {
                    Id = i,
                    CommunicationDeviceEndPoint = $"10.1.1.{i}",
                    Description = $"This a new Description ({i})",
                    ServerEndPoint = $"192.1.1.{i}",
                };

                entityList.Add(entry);
            }

            entityList.ForEach(e => {
                repo.Create(e);
            });

            var allData = repo.GetAll();

            var paging = repo.GetByPaging(10, 5, $"");

            var pagingwhere = repo.GetByPaging(10, 5, $"{nameof(CommInImdb.MapKey)} != 0");

            return;
        }
    }
}

```

**HazelCastUnitOfWork.cs**

```
using Hazelcast.Config;
using Hazelcast.Core;
using System;
using System.Collections.Generic;

namespace MyHazelcastTest {
    public class HazelCastUnitOfWork {
        private static readonly object syncRoot = new object();
        public readonly IHazelcastInstance HazelcastClient;
        private static IHazelcastInstance _hazelcastClient;

        public HazelCastUnitOfWork() {
            if(_hazelcastClient != null) {
                HazelcastClient = _hazelcastClient;
                return;
            }
            lock(syncRoot) {
                if(_hazelcastClient != null) {
                    HazelcastClient = _hazelcastClient;
                    return;
                }

                HazelcastClient = CreateInstance();
            }
        }

        private IHazelcastInstance CreateInstance() {
            try {
                var hazelCastIpAddress = "127.0.0.1:5701";
                var groupId = "myhazelcast";
                var password = "mypassword";
                var nearCacheConfigs = new Dictionary<string,NearCacheConfig>();

                var nearCacheConfig = new NearCacheConfig()
                    .SetInvalidateOnChange(true)
                    .SetEvictionPolicy("Lru")
                    .SetInMemoryFormat(InMemoryFormat.Object);


                var clientConfig = new ClientConfig();
                clientConfig.GetNetworkConfig().AddAddress(hazelCastIpAddress).SetConnectionTimeout(1000 * 60);
                clientConfig.SetGroupConfig(new GroupConfig(groupId,password));

                clientConfig.GetSerializationConfig().AddPortableFactory(1,new MyDataSerializableFactory());                    

                
                clientConfig.SetNearCacheConfigMap(nearCacheConfigs);
                _hazelcastClient = Hazelcast.Client.HazelcastClient.NewHazelcastClient(clientConfig);
                _hazelcastClient.GetLifecycleService().AddLifecycleListener(new LifecycleListener(Action));

                return _hazelcastClient;


            } catch(Exception e) {
                throw new Exception(e.Message);
            }


        }

        private void Action(LifecycleEvent lifecycleEvent) {
        }


        public void Dispose() {

        }

        public HazelCastRepository<CommInImdb> GetRepository(){
            return new HazelCastRepository<CommInImdb>(HazelcastClient);
        }


    }
}
```

**HazelCastRepository.cs**

```
using Hazelcast.Core;
using System.Collections.Generic;
using System.Linq;

namespace MyHazelcastTest {
    public class HazelCastRepository<TEntity> where TEntity : CommInImdb {

        private IHazelcastInstance _hazelcastClient;
        public IMap<string,TEntity> Map { get; }

        public HazelCastRepository(IHazelcastInstance hazelcastClient) {
            _hazelcastClient = hazelcastClient;
            Map = hazelcastClient.GetMap<string,TEntity>(nameof(CommInImdb));            
        }

        public void Lock() {
            var mapLock = _hazelcastClient.GetLock(nameof(CommInImdb));
            mapLock.Lock();
        }

        public void Unlock() {
            var mapLock = _hazelcastClient.GetLock(nameof(CommInImdb));
            mapLock.ForceUnlock();
        }

        public void Create(TEntity entity) {
            Map.Set(entity.MapKey,entity);
        }

        public IEnumerable<TEntity> GetAll() {
            return Map.Values();
        }

        public IEnumerable<TEntity> GetByPaging(int skipCount,int takeCount,string where,params object[] values) {    
            var page = (skipCount / takeCount) + 1;

            if(string.IsNullOrEmpty(where)) {
                var paging = new PagingPredicate(takeCount) {
                    Page = page
                };

                return Map.Values(paging);
            }

            var sqlPredicate = new SqlPredicate(where);
            var pagingPredicate = new PagingPredicate(takeCount,sqlPredicate) {
                Page = page
            };

            return Map.Values(pagingPredicate);
        }
    }
}
```

**MyDataSerializableFactory.cs**

```
using Hazelcast.IO.Serialization;
using System;


namespace MyHazelcastTest {
    public class MyDataSerializableFactory : IPortableFactory {
        public IPortable Create(int classId) {
            var instance = Activator.CreateInstance(typeof(CommInImdb));

            var portableInstance = (IPortable)instance;

            return portableInstance;
        }
    }
}
```


**CommInImdb.cs**

```
using AutoMapper;
using Hazelcast.IO.Serialization;
using System;

namespace MyHazelcastTest {
    [Serializable]
    public class CommInImdb : IPortable, IComparable {
        public int Id { get; set; }
        public string MapKey { get; set; } = Guid.NewGuid().ToString();

        [IgnoreMap]
        public int HzClassId { get; set; } = 1;

        [IgnoreMap]
        public int HzFactoryId {
            get { return this.HzClassId; }
            set {
                value = HzClassId;
            }
        }
    
        public string ServerEndPoint { get; set; }
        public string CommunicationDeviceEndPoint { get; set; }
        public string Description { get; set; }

        public int CompareTo(object obj) {
            return HzClassId;
        }

        public int GetClassId() {
            return HzClassId;
        }

        public int GetFactoryId() {
            return HzClassId;
        }

        public void ReadPortable(IPortableReader reader) {
            MapKey = reader.ReadUTF(nameof(MapKey));
            HzClassId = reader.ReadInt(nameof(HzClassId));
            HzFactoryId = reader.ReadInt(nameof(HzFactoryId));
            Id = reader.ReadInt(nameof(Id));
            ServerEndPoint = reader.ReadUTF(nameof(ServerEndPoint));
            CommunicationDeviceEndPoint = reader.ReadUTF(nameof(CommunicationDeviceEndPoint));
            Description = reader.ReadUTF(nameof(Description));
        }

        public void WritePortable(IPortableWriter writer) {
            writer.WriteInt(nameof(HzClassId), HzClassId);
            writer.WriteInt(nameof(HzFactoryId), HzFactoryId);
            writer.WriteUTF(nameof(MapKey), MapKey);
            writer.WriteInt(nameof(Id), Id);
            writer.WriteUTF(nameof(ServerEndPoint), ServerEndPoint);
            writer.WriteUTF(nameof(CommunicationDeviceEndPoint), CommunicationDeviceEndPoint);
            writer.WriteUTF(nameof(Description), Description);
        }

    }
}

```

After all I have tested it with 50 records again, and yes it is a fail.

https://i.imgur.com/DWA0sX7.png
https://i.imgur.com/Nd5mO72.png

If I try it with 10 records. Surprise!
https://i.imgur.com/liAt66j.png
https://i.imgur.com/luAG6L2.png

However run it again and you will get a class-id exception. That's also not stable.

**Comment by stalek71** [comment] 2019-02-14 12:35
Hi @hkilimci,
in my case I receive exception about missing portable factory all the time.
What .Net client version and server/cluster version do you use?

**Comment by hkilimci** [comment] 2019-02-18 14:22
Hi @stalek71 ,

I use near cache but not for the all maps. Does it make difference? 

I use the lastest .net client version and the latest hazelcast version. 

Below is showing my java side code of hazelcast server, only 5 lines of code:

```
import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MulticastConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

public class MyHazelCastMain {
    public static void main(String[] args) {
        Config config = new Config();
        config.setInstanceName("myhazelcast");
        config.getGroupConfig().setName("myhazelcast").setPassword("mypassword");
        config.getNetworkConfig().setPort( 5701 ).setPortAutoIncrement( true ).setJoin(new JoinConfig().setMulticastConfig(new MulticastConfig().setEnabled(false)));
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
    }
}
```

**Comment by stalek71** [comment] 2019-02-20 16:01
Yes, it makes the difference.
Please just check short explanation here:
https://blog.hazelcast.com/pro-tip-near-cache/

**Comment by hkilimci** [comment] 2019-02-21 06:49
It doesn't say anything about Paging on the link you have sent. The link for the detail page is broken: http://www.hazelcast.com/docs/2.3/manual/single_html/#MapNearCache

**Comment by stalek71** [comment] 2019-02-21 09:49
I will check the case with near cache enabled for other map yet.

**Comment by sancar** [comment] 2019-03-01 12:53
@hkilimci and @iozcelik 
Paging Predicate requires registering class on the server side. You have to register your classes on the server. 
SQL Predicate does not require registering your classes. So both behaviors are expected. 
You need to do the following call on the java side also to fix this problem. 
```
clientConfig.GetSerializationConfig().AddPortableFactory(1,new MyDataSerializableFactory());
```

**Comment by hkilimci** [comment] 2019-03-01 13:09
@sancar Thanks for your reply.
Is it a must? Because as you can see from my above posts, it works when the map is empty or sometimes the map has very few items.
Also, it is not very good way to create the same classes and register them on config on java side as we use C# client but that's completely off topic.

**Comment by sancar** [comment] 2019-03-01 13:16
Yes, currently it is a must. It sometimes works because these are the cases where sorting is not necessary(empty or a few times). 
In general use case to use paging predicate you need sorting on the server side. 

We have a prd to work on to eliminate this server-side requirement. We will be attaching this issue as the community request.

**Comment by zpqrtbnk** [comment] 2020-12-09 07:39
Reproduced on upcoming 4.0 client. Have created a `Hazelcast.Tests.Support.Issue212` test class that reproduce.

Checking with server team for updates on the server side, as this really is a server-side issue.

**Comment by zpqrtbnk** [comment] 2020-12-09 07:51
Had confirmation that this depends on server-side work that is still in backlog. Moving this issue back to backlog.

**Comment by emreyigit** [comment] 2023-03-28 08:28
Predicates marked as obsolete.

**Closed by emreyigit** 2023-03-28 08:28 UTC
Labels: Type: Defect, Priority: High, Source: Community
